# Generated by Django 2.2.7 on 2019-12-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unblockings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_ci', models.CharField(max_length=10)),
                ('incident_num', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Р', 'Разблокирован'), ('П', 'Перенесен')], max_length=1)),
                ('date', models.DateField()),
                ('row_adder', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=300)),
            ],
        ),
    ]
