# Generated by Django 2.2.7 on 2019-12-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unblockings',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
